### PR TITLE
[CH-359] fix libhdfs3 conf not correctly set bug

### LINKED ISSUE #359: HDFS config is not correctly set for libhdfs3
> You have to provide the following information whenever possible.

**Describe what's wrong**

> When I run spark on hadoop cluster using gluten with ch backend, the job failed due to can not paser the hdfs cluster as bellow. I have set --conf spark.gluten.sql.columnar.backend.ch.runtime_conf.hdfs.libhdfs3_conf=/etc/hadoop/conf/hdfs-site.xml
image

### PR DESCRIPTION
**Pull request by shuai-xu**
### Changelog category (leave one):
- Bug Fix (user-visible misbehavior in official stable or prestable release)

### Changelog entry (a user-readable short description of the changes that goes to CHANGELOG.md):
Fix the bug that libhdfs config is not correctly set
This close #359

### CODE REVIEW

**Comment by kyligence-git** [comment]
Can one of the admins verify this patch?

File: utils/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp [hunk 1]
```diff
@@ -62,10 +62,12 @@ class HDFSFileReadBufferBuilder : public ReadBufferBuilder
         Poco::URI file_uri(file_info.uri_file());
         std::unique_ptr<DB::ReadBuffer> read_buffer;
         /// Need to set "hdfs.libhdfs3_conf" in global settings
-        if (context->getConfigRef().getString("hdfs.libhdfs3_conf", "").empty())
+        std::string libhdfs3_conf = context->getConfigRef().getString("hdfs.libhdfs3_conf", "");
+        if (libhdfs3_conf.empty())
         {
             throw DB::Exception(DB::ErrorCodes::BAD_ARGUMENTS, "Not found hdfs.libhdfs3_conf");
         }
+        setenv("LIBHDFS3_CONF", libhdfs3_conf.c_str(), 1);
```
Comment (lgbo-ustc) [inline utils/local-engine/Storages/SubstraitSource/ReadBufferBuilder.cpp:70]: If we don't use HA, this should not be called

**Comment by liuneng1994** [comment]
test this please

**Review by liuneng1994 — APPROVED** [review]
